import { exec, execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";
import type { Incident, ProposedFix } from "./types.js";

const execFileAsync = promisify(execFile);
const execAsync = promisify(exec);

export interface GitFixResult {
  branchName: string;
  commitSha?: string;
  pushed: boolean;
  prBody: string;
  error?: string;
}

export interface VerificationResult {
  passed: boolean;
  output: string;
  exitCode: number;
}

export interface AutoMergeResult {
  success: boolean;
  mergeCommitSha?: string;
  error?: string;
}

export interface AutoRevertResult {
  success: boolean;
  revertedSha?: string;
  error?: string;
}

export class GitFixDispatcher {
  /**
   * Retrieves the current HEAD commit short hash, or a fallback deterministic hash.
   */
  public async getGitHeadSha(cwd: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync("git", ["rev-parse", "--short", "HEAD"], { cwd });
      return stdout.trim();
    } catch {
      return Math.random().toString(36).slice(2, 10);
    }
  }

  /**
   * Creates a fix branch `zencode/fix_{sha}`, writes patched files, and commits them.
   */
  public async createFixBranchAndCommit(
    incident: Incident,
    fix: ProposedFix,
  ): Promise<GitFixResult> {
    const cwd = incident.workspaceDir;
    const branchName = `zencode/fix_${incident.sha}`;

    try {
      // 1. Verify git repo
      await execFileAsync("git", ["rev-parse", "--is-inside-work-tree"], { cwd });

      // 2. Checkout new branch from current HEAD
      await execFileAsync("git", ["checkout", "-b", branchName], { cwd }).catch(async () => {
        // If branch already exists, switch to it
        await execFileAsync("git", ["checkout", branchName], { cwd });
      });

      // 3. Write patched files
      for (const patch of fix.patchFiles) {
        const fullPath = path.isAbsolute(patch.path) ? patch.path : path.join(cwd, patch.path);
        await fs.mkdir(path.dirname(fullPath), { recursive: true });
        await fs.writeFile(fullPath, patch.newContent, "utf8");
        await execFileAsync("git", ["add", patch.path], { cwd });
      }

      // 4. Commit
      const commitMsg = `${fix.suggestedCommitMessage}\n\nIncident-ID: ${incident.id}\nAuto-generated by Zencode Self-Healing Engine`;
      await execFileAsync("git", ["commit", "-m", commitMsg], { cwd }).catch(() => ({
        stdout: "",
        stderr: "",
      }));

      const commitSha = await this.getGitHeadSha(cwd);
      const prBody = this.generatePrDescription(incident, fix, branchName);

      return {
        branchName,
        commitSha,
        pushed: false,
        prBody,
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      return {
        branchName,
        pushed: false,
        prBody: this.generatePrDescription(incident, fix, branchName),
        error: msg,
      };
    }
  }

  /**
   * Pushes the fix branch to the git remote.
   */
  public async pushFixBranch(
    cwd: string,
    branchName: string,
  ): Promise<{ success: boolean; output?: string; error?: string }> {
    try {
      const { stdout, stderr } = await execFileAsync("git", ["push", "-u", "origin", branchName], {
        cwd,
        timeout: 30000,
      });
      return { success: true, output: stdout || stderr };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, error: msg };
    }
  }

  /**
   * Generates a comprehensive Pull Request / Review description.
   */
  public generatePrDescription(incident: Incident, fix: ProposedFix, branchName: string): string {
    const patchSummary = fix.patchFiles.map((p) => `- \`${p.path}\``).join("\n");

    return `## 🛠️ Zencode Self-Healing Auto-Patch: \`${branchName}\`

### 1. Incident Overview
- **Incident ID**: \`${incident.id}\`
- **Source**: \`${incident.source}\` (${incident.hookName || incident.toolName || "runtime"})
- **Exit Code**: \`${incident.exitCode ?? "N/A"}\`
- **Root Cause**: ${fix.rootCause}

### 2. Failure Telemetry (stderr)
\`\`\`text
${incident.stderr?.trim() || "(No stderr captured)"}
\`\`\`

### 3. Proposed Fix
${fix.summary}

**Modified Files**:
${patchSummary}

### 4. Verification & Testing Steps
${fix.verificationSteps.map((step, idx) => `${idx + 1}. ${step}`).join("\n")}

---
### 5. Review & Merge Instructions
Review the diff in this branch:
\`\`\`bash
git checkout ${branchName}
git diff HEAD~1
\`\`\`
To merge into your active branch:
\`\`\`bash
git merge ${branchName}
\`\`\`
`;
  }

  /**
   * Retrieves the current branch name, falling back to 'main'.
   */
  public async getCurrentBranch(cwd: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd });
      const branch = stdout.trim();
      return branch === "HEAD" ? "main" : branch;
    } catch {
      return "main";
    }
  }

  /**
   * Runs automated test verification in the workspace.
   */
  public async runTestVerification(
    cwd: string,
    testCommand: string,
    timeoutMs = 60000,
  ): Promise<VerificationResult> {
    try {
      const { stdout, stderr } = await execAsync(testCommand, {
        cwd,
        timeout: timeoutMs,
        maxBuffer: 5 * 1024 * 1024,
      });
      const output = `${stdout || ""}\n${stderr || ""}`.trim();
      return {
        passed: true,
        output,
        exitCode: 0,
      };
    } catch (err: unknown) {
      let exitCode = 1;
      let output = "";
      if (err && typeof err === "object") {
        const errorRecord = err as {
          code?: number;
          stdout?: string;
          stderr?: string;
          message?: string;
        };
        exitCode = typeof errorRecord.code === "number" ? errorRecord.code : 1;
        output =
          `${errorRecord.stdout || ""}\n${errorRecord.stderr || ""}\n${errorRecord.message || ""}`.trim();
      } else {
        output = String(err);
      }
      return {
        passed: false,
        output,
        exitCode,
      };
    }
  }

  /**
   * Auto-merges the fix branch into the target branch upon 100% test pass.
   * Cleans up the ephemeral fix branch after successful merge.
   */
  public async autoMergeBranch(
    cwd: string,
    sourceBranch: string,
    targetBranch: string,
  ): Promise<AutoMergeResult> {
    try {
      // 1. Checkout target branch
      await execFileAsync("git", ["checkout", targetBranch], { cwd });

      // 2. Perform merge with clear [AUTO-HEAL] commit message
      const mergeMsg = `merge(self-healing): auto-merge fix from ${sourceBranch} [AUTO-HEAL]`;
      await execFileAsync("git", ["merge", "--no-ff", "-m", mergeMsg, sourceBranch], { cwd });

      const mergeCommitSha = await this.getGitHeadSha(cwd);

      // 3. Delete ephemeral fix branch
      await execFileAsync("git", ["branch", "-D", sourceBranch], { cwd }).catch(() => undefined);

      return {
        success: true,
        mergeCommitSha,
      };
    } catch (err: unknown) {
      // On conflict or merge failure, abort merge immediately
      await execFileAsync("git", ["merge", "--abort"], { cwd }).catch(() => undefined);
      const msg = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        error: `Auto-merge conflict or failure: ${msg}`,
      };
    }
  }

  /**
   * Instantly reverts workspace to the original SHA and deletes the failed fix branch.
   * Ensures zero residual dirty files or corrupted states.
   */
  public async autoRevertFix(
    cwd: string,
    sourceBranch: string,
    originalSha: string,
    targetBranch = "main",
  ): Promise<AutoRevertResult> {
    try {
      // 1. Abort any merge in progress
      await execFileAsync("git", ["merge", "--abort"], { cwd }).catch(() => undefined);

      // 2. Hard reset and clean working tree
      await execFileAsync("git", ["reset", "--hard"], { cwd }).catch(() => undefined);
      await execFileAsync("git", ["clean", "-fd"], { cwd }).catch(() => undefined);

      // 3. Checkout target branch or original SHA
      await execFileAsync("git", ["checkout", "-f", targetBranch], { cwd }).catch(async () => {
        await execFileAsync("git", ["checkout", "-f", originalSha], { cwd });
      });

      // 4. Force delete the failed fix branch
      if (sourceBranch) {
        await execFileAsync("git", ["branch", "-D", sourceBranch], { cwd }).catch(() => undefined);
      }

      const revertedSha = await this.getGitHeadSha(cwd);
      return {
        success: true,
        revertedSha,
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        error: `Auto-revert failed: ${msg}`,
      };
    }
  }
}
